[env:esp32-s3-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.32/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags =
    -Wno-unused-variable
    -Wno-unused-but-set-variable
    -Wunreachable-code
lib_deps =
    SPI
    Wire
